src/ndj/DGameBundle/Entity/Bestiaire.php
<?php

namespace ndj\DGameBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use ndj\DGameBundle\Util\Tools;
use ndj\DGameBundle\Util\caracs;

/**
 * Bestiaire
 *
 * @ORM\Table(name="BESTIAIRE")
 * @ORM\Entity(repositoryClass="ndj\DGameBundle\Repository\BestiaireRepository")
 */
class Bestiaire {

   // use LevelableTrait;
  //  use PositionnableTrait;
  //  use AchetableTrait;
  //  use SerialisableArrayTrait;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="PRENOM", type="string", length=45, nullable=false)
     */
    private $prenom;

    /**
     * @var integer
     *
     * @ORM\Column(name="ACROBATIE", type="smallint", nullable=false)
     */
    private $acrobatie;

    /**
     * @var integer
     *
     * @ORM\Column(name="BAGARRE", type="smallint", nullable=false)
     */
    private $bagarre;

    /**
     * @var integer
     *
     * @ORM\Column(name="CHARME", type="smallint", nullable=false)
     */
    private $charme;

    /**
     * @var integer
     *
     * @ORM\Column(name="ACUITE", type="smallint", nullable=false)
     */
    private $acuite;

    /**
     * @var integer
     *
     * @ORM\Column(name="AGE", type="smallint", nullable=false)
     */
    private $age;

    /**
     * @var integer
     *
     * @ORM\Column(name="EXPERIENCE", type="integer", nullable=false)
     */
    private $experience;

    /**
     * @var integer
     *
     * @ORM\Column(name="RENOMMEE", type="smallint", nullable=false)
     */
    private $renommee;

    /**
     * @var integer
     *
     * @ORM\Column(name="PVIE", type="smallint", nullable=false)
     */
    private $pvie;

    /**
     * @var integer
     *
     * @ORM\Column(name="PVIE_MAX", type="smallint", nullable=false)
     */
    private $pvieMax;

    /**
     * @var boolean
     *
     * @ORM\Column(name="REPOS", type="boolean", nullable=false)
     */
    private $repos;

    /**
     * @var boolean
     *
     * @ORM\Column(name="A_VENDRE", type="boolean", nullable=false)
     */
    private $aVendre;

    /**
     * @var float
     *
     * @ORM\Column(name="COUT", type="decimal", nullable=false)
     */
    private $cout;

    /**
     * @var string
     *
     * @ORM\Column(name="POSITION", type="string", length=45, nullable=true)
     */
    private $position;

    /**
     * @var string
     *
     * @ORM\Column(name="POUVOIRS", type="string", length=45, nullable=true)
     */
    private $pouvoirs;

    /**
     * @var string
     *
     * @ORM\Column(name="TALENTS", type="string", length=255, nullable=true)
     */
    private $talents;

    /**
     * @var string
     *
     * @ORM\Column(name="ENVOUTEMENT", type="string", length=255, nullable=true)
     */
    private $envoutement;

    /**
     * @var string
     *
     * @ORM\Column(name="ORDRE", type="string", length=255, nullable=true)
     */
    private $ordre;

    /**
     * @var integer
     *
     * @ORM\Column(name="POINTS", type="integer", nullable=false)
     */
    private $points;

    /**
     * @var \Donjon
     *
     * @ORM\ManyToOne(targetEntity="Donjon",  inversedBy="bestiaires")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idDONJON", referencedColumnName="id")
     * })
     */
    private $iddonjon;

    /**
     * @var \Creature
     *
     * @ORM\ManyToOne(targetEntity="Creature", inversedBy="bestiaires")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idCREATURE", referencedColumnName="id")
     * })
     */
    private $idcreature;

    /**
     * @var \Piece
     *
     * @ORM\ManyToOne(targetEntity="Piece", inversedBy="bestiaires")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idPIECE", referencedColumnName="id")
     * })
     */
    private $idpiece;

    /**
     * @ORM\OneToMany(targetEntity="ndj\DGameBundle\Entity\Inventaire", mappedBy="idbestiaire")
     */
    private $inventaires;

    public function addInventaire(Inventaire $inventaire) {
        $this->inventaires[] = $inventaire;
        $inventaire->setIdbestiaire($this);
        return $this;
    }

    public function removeInventaire(Inventaire $inventaire) {
        $this->inventaires->removeElement($inventaire);
        $inventaire->setIdbestiaire(null);
    }

    public function hasInventaire(Inventaire $inventaire) {
        return $this->inventaires->contains($inventaire);
    }

    public function getInventaires() {
        return $this->inventaires;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->inventaires = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     * @return Bestiaire
     */
    public function setPrenom($prenom) {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string 
     */
    public function getPrenom() {
        return $this->prenom;
    }

    public function getNom() {
        return $this->getPrenom();
    }

    /**
     * Set acrobatie
     *
     * @param integer $acrobatie
     * @return Bestiaire
     */
    public function setAcrobatie($acrobatie) {
        $this->acrobatie = $acrobatie;

        return $this;
    }

    /**
     * Get acrobatie
     *
     * @return integer 
     */
    public function getAcrobatie() {
        return $this->acrobatie;
    }

    /**
     * Set bagarre
     *
     * @param integer $bagarre
     * @return Bestiaire
     */
    public function setBagarre($bagarre) {
        $this->bagarre = $bagarre;

        return $this;
    }

    /**
     * Get bagarre
     *
     * @return integer 
     */
    public function getBagarre() {
        return $this->bagarre;
    }

    /**
     * Set charme
     *
     * @param integer $charme
     * @return Bestiaire
     */
    public function setCharme($charme) {
        $this->charme = $charme;

        return $this;
    }

    /**
     * Get charme
     *
     * @return integer 
     */
    public function getCharme() {
        return $this->charme;
    }

    /**
     * Set acuite
     *
     * @param integer $acuite
     * @return Bestiaire
     */
    public function setAcuite($acuite) {
        $this->acuite = $acuite;

        return $this;
    }

    /**
     * Get acuite
     *
     * @return integer 
     */
    public function getAcuite() {
        return $this->acuite;
    }

    /**
     * Set age
     *
     * @param integer $age
     * @return Bestiaire
     */
    public function setAge($age) {
        $this->age = $age;

        return $this;
    }

    /**
     * Get age
     *
     * @return integer 
     */
    public function getAge() {
        return $this->age;
    }

    /**
     * Set experience
     *
     * @param integer $experience
     * @return Bestiaire
     */
    public function setExperience($experience) {
        $this->experience = $experience;

        return $this;
    }

    /**
     * Get experience
     *
     * @return integer 
     */
    public function getExperience() {
        return $this->experience;
    }

    /**
     * Set renommee
     *
     * @param integer $renommee
     * @return Bestiaire
     */
    public function setRenommee($renommee) {
        $this->renommee = $renommee;

        return $this;
    }

    /**
     * Get renommee
     *
     * @return integer 
     */
    public function getRenommee() {
        return $this->renommee;
    }

    /**
     * Set pvie
     *
     * @param integer $pvie
     * @return Bestiaire
     */
    public function setPvie($pvie) {
        $this->pvie = $pvie;

        return $this;
    }

    /**
     * Get pvie
     *
     * @return integer 
     */
    public function getPvie() {
        return $this->pvie;
    }

    /**
     * Set pvieMax
     *
     * @param integer $pvieMax
     * @return Bestiaire
     */
    public function setPvieMax($pvieMax) {
        $this->pvieMax = $pvieMax;

        return $this;
    }

    /**
     * Get pvieMax
     *
     * @return integer 
     */
    public function getPvieMax() {
        return $this->pvieMax;
    }

    /**
     * Set repos
     *
     * @param boolean $repos
     * @return Bestiaire
     */
    public function setRepos($repos) {
        $this->repos = $repos;

        return $this;
    }

    /**
     * Get repos
     *
     * @return boolean 
     */
    public function getRepos() {
        return $this->repos;
    }

    /**
     * Set aVendre
     *
     * @param boolean $aVendre
     * @return Bestiaire
     */
    public function setAVendre($aVendre) {
        $this->aVendre = $aVendre;

        return $this;
    }

    /**
     * Get aVendre
     *
     * @return boolean 
     */
    public function getAVendre() {
        return $this->aVendre;
    }

    /**
     * Set cout
     *
     * @param float $cout
     * @return Bestiaire
     */
    public function setCout($cout) {
        $this->cout = $cout;

        return $this;
    }

    /**
     * Get cout
     *
     * @return float 
     */
    public function getCout() {
        return $this->cout;
    }

    /**
     * Set position
     *
     * @param string $position
     * @return Bestiaire
     */
    public function setPosition($position) {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return string 
     */
    public function getPosition() {
        return $this->position;
    }

    /**
     * Set pouvoirs
     *
     * @param string $pouvoirs
     * @return Bestiaire
     */
    public function setPouvoirs($pouvoirs) {
        $this->pouvoirs = $pouvoirs;

        return $this;
    }

    /**
     * Get pouvoirs
     *
     * @return string 
     */

src/ndj/DGameBundle/Entity/OuvrableTrait.php
<?php

namespace ndj\DGameBundle\Entity;

trait OuvrableTrait {

    abstract public function setClose();

    abstract public function setOpen();

    abstract public function getEtat();

    abstract public function setEtat($e);


    /**
     *  valeur de ETAT :
     * -X: ferme dans X tours
     * -1: ferme au prochain tour
     * 0: désactivé
     * 1: en construction (PC, PA illimité)
     * 2: ouvert
     */
    /* static public $_etat = array(
      -1 => 'Fermé dans {X} tour(s)',
      0 => 'Désactivé',
      1 => 'En construction',
      2 => 'Ouvert aux aventuriers'
      ); */

    public function getEtats() {
        return array(
            -3 => 'Fermé dans 3 tour(s)',
            -2 => 'Fermé dans 2 tour(s)',
            -1 => 'Fermé dans 1 tour(s)',
            0 => 'Désactivé',
            1 => 'En construction',
            2 => 'Ouvert au aventurier'
        );
    }

    public function isClosingSoon() {
        return ($this->getETAT() < 0) ? $this->getETAT() : false;
    }

    public function isOpen() {
        return ($this->getETAT() == 2);
    }

    public function isBuilding() {
        return ($this->getETAT() == 1);
    }

    public function displayEtat() {
        //if ($this->getETAT() >= 0) {
        return $this->getEtats()[$this->getETAT()];
        /* } else {
          $ret = self::$_etat[-1];
          $ret = str_replace('{X}', $this->getETAT() * -1, $ret);
          return $ret;
          } */
    }

    public function setCloseDelay() {
        if ($this->isOpen()) {
            $this->setEtat(-3);
            return true;
        }
        return false;
    }

}

src/ndj/DGameBundle/Resources/views/Organisation/fiche.html.twig
<table>
<tbody>
	<tr>
		<td>Nom : </td> <td>{{orga.nom}}</td>
	<tr>
		<td>Description : </td> <td>{{orga.description|nl2br}}</td>
	</tr>
	{% if orga.isMembreActif(aventurier) or (orga.public and not orga.chef.cacher)  %}
	<tr>
		<td>Chef : </td> <td><a href="javascript:void(0)" onclick="displayFiche('aventurier',{{orga.chef.idaventurier.id}})">{{orga.chef.idaventurier.nom}}</a></td>
	</tr>
	{% endif %}
</tbody>
</table>

src/ndj/DGameBundle/Resources/views/Organisation/fichedetaillee.html.twig
{% set appm = orga.getOrganisationAppartenance(aventurier) %}
<div id="aventurier-orga-tabs">
<ul>
    <li><a href="#orga-tabs-1">Généralité</a></li>
    <li><a href="#orga-tabs-2">Vous</a></li>
    <li><a href="#orga-tabs-3">Membres actifs</a></li>
    <li><a href="#orga-tabs-4">Membres inactifs</a></li>
    {# <li><a href="#orga-tabs-5">Inventaire</a></li> #}
</ul>

{# résumé #}
<div id="orga-tabs-1">
    <div>{% include 'ndjDGameBundle:Organisation:fiche.html.twig' with {orga:orga,aventurier:aventurier} %}</div>
    <div></div>
</div>
        
{# appartenance #}
<div id="orga-tabs-2">
    {% if appm.is('chef') %}<strong>Vous êtes actuellement le chef de la guilde.</strong>{% endif %}
    <div>Votre titre : {% if appm.titre is not empty %}{{appm.titre}}{% else %}<i>Aucun</i>{%endif%}</div>
    <div title="Cacher votre appartenance signifie que votre appartenance sera cachée aux membres extérieurs à l'organisation.">
        <label for="orgappmbcache">Cacher votre appartenance : </label><input type="checkbox" onchange="organisation_mbsetcacher({{appm.idorganisation.id}},$(this).is(':checked'))" id="orgappmbcache" {% if appm.cacher %}checked="checked"{%endif%}/>
    </div>
    <div>
        <table border="1">
            <thead>
                <tr>
                    <th>Vous avez les <u>droits</u> suivants...</th>
                    <th>... les <u>actions</u> suivantes vous sont donc accessibles :</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <ul>
                    {% for d in appm.getDroits()|split(',') %}
                                <li>{{ appm.getDroitLabel(d) }}</li>
                    {% endfor %}
                                </ul>
                    </td>
                    <td>
                        <ul>
                    {% for a in appm.getActionsPossibles() %}
                                <li>{{ appm.getActionLabel(a) }}</li>
                    {% endfor %}
                                </ul>
                    </td>
                </tr>
            </tbody>
        </table>
     </div>
</div>
        
{# membre #}
<div id="orga-tabs-3">
{% if appm.actionPossible('listeMembre') %}
        {% include 'ndjDGameBundle:Organisation:listemembre.html.twig' with {orga:orga,actif:1,liste:orga.getMembresActif()} %}
{% else %}
        <p>Vous n'avez pas accès à la liste des membres.</p>
{% endif %}
</div>

{# membre autre #}
<div id="orga-tabs-4">
{% if appm.actionPossible('listeMembre') %}
        {% include 'ndjDGameBundle:Organisation:listemembre.html.twig' with {orga:orga,actif:0,liste:orga.getMembresInactif()} %}
{% else %}
        <p>Vous n'avez pas accès à la liste des membres.</p>
{% endif %}
</div>

{# inventaire #}
{#<div id="orga-tabs-5">
<i>à venir !</i>
</div>#}

</div>

<script> $(function() { $( "#aventurier-orga-tabs" ).tabs({ heightStyle: "fill" }); }); </script>

src/ndj/DGameBundle/Resources/views/Organisation/form.creer.html.twig
<form action="{{ path('organisation_creer') }}" method="post" {{ form_enctype(form) }} onsubmit="return organisation_submit(this);">
<p>{{ form_errors(form) }}</p>

<table>
	<tr>
		<td>Nom : </td>
		<td>{{ form_widget(form.nom) }} <p>{{form_errors(form.nom)}}</p></td>
	</tr>
	
	<tr>
		<td> Description : </td>
		<td>
		<div class="small">(En quelques mots/phrases, décrire le(s) but(s) de l'organisation, ses critères d'admission, etc)</div>
		{{ form_widget(form.description) }} <p>{{form_errors(form.description)}}</p></td>
	</tr>
	<tr>
		<td>Nombre de membre maximum : </td>
		<td>
			<div class="small">(0 pour illimité)</div>
		{{ form_widget(form.nombrembmax) }} <p>{{form_errors(form.nombrembmax)}}</p></td>
	</tr>
	
	{% if cat == 'guilde' %}
		
	<tr>
		<td>Charte de la guilde : </td>
		<td>
		<div class="small">(la charte est à usage interne. Accessible uniquement aux membres, elle décrit principalement les règles de fonctionnement de votre organisation).</div>
		{{ form_widget(form.charte) }} <p>{{form_errors(form.charte)}}</p></td>
	</tr>
		
	<tr>
		<td>Blason : </td>
		<td>{{ form_widget(form.blason) }} <p>{{form_errors(form.blason)}}</p></td>
	</tr>
		
	<tr>
		<td>Mode de gestion : </td>
		<td>
		<div class="small">(Le mode de gestion concerne la gestion des inscriptions.)</div>
		{{ form_widget(form.gestion) }} <p>{{form_errors(form.gestion)}}</p></td>
	</tr>
		
	<tr>
		<td> Visibilité : </td>
		<td>
		<div class="small">(Choisir "cachée" signifie seuls le nom et la description de la guilde sera visible. On ne pourra y rentrer que sur invitation. )</div>
		{{ form_widget(form.public) }} <p>{{form_errors(form.public)}}</p></td>
	</tr>
	
	<tr>
		<td> Prix d'entrée : </td>
		<td>
		<div class="small">(Le montant qu'un personnage doit dépenser pour rentrer dans la guilde.)</div>
		{{ form_widget(form.prixIn) }} <p>{{form_errors(form.prixIn)}}</p></td>
	</tr>
	
	<tr>
		<td> Cotisation : </td>
		<td>
		<div class="small">(Le montant dont un personnage doit s'acquitter régulièrment en payant la guilde.)</div>
		{{ form_widget(form.prixCot) }} <p>{{form_errors(form.prixCot)}}</p></td>
	</tr>
	{% endif %}
</table>

{{ form_rest(form) }}

<input type="submit" value="Envoyer" />

</form>

<script>
$(function(){
	$('#form_nombrembmax').spinner({min:0,step:1});
	$('#form_prixIn, #form_prixCot').spinner({min:0,step:1});
});
</script>

src/ndj/DGameBundle/Resources/views/Organisation/liste.html.twig
{% if liste|length == 0 %}
<p>Il n'y a aucune organisation.</p>
{% else %}
<table id="listeOrganisation">
<thead>
<tr>
<th>Nom</th>
<th>Chef</th>
<th></th>
</tr>
</thead>
<tbody>
{% for o in liste %}
	<tr>
		<td title="{{o.description|nl2br}}"><a href="javascript:void(0)" onclick="displayFiche('organisation',{{o.id}})">{{o.nom}}</a></td>
		<td>
		{% if o.public %} <a href="javascript:void(0)" onclick="displayFiche('aventurier',{{o.chef.id}})">{{o.chef.nom}}</a> 
		{% else %} ? {% endif %}
		</td>
		<td>
			{% if o.public %} Demande d'adhésion {% endif %}
			Envoyer un message
                        {% if o.isMembreActif(aventurier) %}
                        <a href="javascript:void(0);" onclick="organisation_panel({{o.id}},'{{o.nom}}')">Voir</a>
                        {% endif %}
		</td>
	</tr>
{% endfor %}
</tbody>
</table>


<div id="listeOrganisation-pager" class="pager"> <form> <span class="first pointer">&lt;&lt;</span> <span class="prev pointer">&lt;</span> <span class="smaller pagedisplay"></span> <span class="pointer next">&gt;</span> <span class="pointer last">&gt;&gt;</span> </form></div>

<script>
$('#listeOrganisation > tbody > tr > td ').tooltip();
$(document).ready(function() {
$("#listeOrganisation").tablesorter({widthFixed:true,widgets:["zebra"]})
	.tablesorterPager({container: $("#listeOrganisation-pager"), output: "{page} / {totalPages}"});
});</script>
{% endif %}

src/ndj/DGameBundle/Resources/views/Organisation/listemembre.html.twig
{% set droits = orga.getDroitsPossibles() %}
{% set appm = orga.getOrganisationAppartenance(aventurier) %}
{% set pkey = orga.id ~ actif ~ liste|length ~ actif ~ random(99)%}
<table id="listeMembre{{pkey}}" border="1">
<thead>
    <tr>
        <th rowspan="2">Nom</th>
        <th rowspan="2">Titre</th>
        <th rowspan="2">Etat</th>
        <th rowspan="2">Actions</th>
        {% if appm.actionPossible('gererDroits') and actif %}<th colspan="10">Droits (<a href="javascript:void(0);">?</a>)</th>{%endif%}
    </tr>
    {% if appm.actionPossible('gererDroits') and actif %}
    <tr>
        <th>Chef</th>
        <th title="Administrateur">Adm</th>
        <th title="Gestion des droits">G.D.</th>
        <th title="Gestion de l'agent">G.A.</th>
        <th title="Gestion des objets">G.O.</th>
        <th title="Gestion des membres">G.M.</th>
        <th title="Voir l'argent">A</th>
        <th title="Voir les objets">O</th>
        <th title="Voir les membres">M</th>
        <th title="Inviter un membre">Inv.</th>
    </tr>
    {% endif %}
</thead>
<tbody>
{% for a in liste %}
    <tr>
        <td><a href="javascript:void(0)" onclick="displayFiche('aventurier',{{a.idaventurier.id}})">{{a.idaventurier.nom}}</a></td>
        <td><span class="orgaapp-orga-titre orgaapp-orga-titre-{{a.idorganisation.id}}-{{a.idaventurier.id}}" data="{{a.idaventurier.id}}">{{a.titre}}</span></td>
        <td>{{a.etat}}</td>
        <td>
{% if a.etat == 'demande' %}
            {%if appm.actionPossible('validerMembre')%}<a href="javascript:void(0);" onclick="organisation_mbsetetat('{{ path('organisationapp_validerdemande',{orga:orga.id,id:a.idaventurier.id,valid:1}) }}','{{ path('organisationapp_listemembre',{'id':orga.id,actif:actif}) }}',$('#listeMembre{{pkey}}').parent())">Accepter</a>{% endif %}
            {%if appm.actionPossible('bannirMembre')%} <a href="javascript:void(0);" onclick="organisation_mbsetetat('{{ path('organisationapp_validerdemande',{orga:orga.id,id:a.idaventurier.id,valid:0}) }}','{{ path('organisationapp_listemembre',{'id':orga.id,actif:actif}) }}',$('#listeMembre{{pkey}}').parent())">Refuser</a>{% endif %}
{% elseif a.etat == 'invite' %}
            <a href="javascript:void(0);" onclick="organisation_mbsetetat('{{ path('organisationapp_validerdemande',{orga:orga.id,id:a.idaventurier.id,valid:0}) }}','{{ path('organisationapp_listemembre',{'id':orga.id,actif:actif}) }}',$('#listeMembre{{pkey}}').parent())">Refuser</a>
{% elseif a.etat in ['refus','ancien','exclu'] %}
            {%if appm.actionPossible('inviterMembre')%}<a href="javascript:void(0);" onclick="organisation_mbsetetat('{{ path('organisationapp_inviter',{orga:orga.id,id:a.idaventurier.id}) }}','{{ path('organisationapp_listemembre',{'id':orga.id,actif:actif}) }}',$('#listeMembre{{pkey}}').parent())">re-Inviter</a>{%endif%}
            {%if appm.actionPossible('gererDroits')%}<a href="javascript:void(0);" onclick="organisation_mbsetetat('{{ path('organisationapp_radier',{orga:orga.id,id:a.idaventurier.id}) }}','{{ path('organisationapp_listemembre',{'id':orga.id,actif:actif}) }}',$('#listeMembre{{pkey}}').parent())" title="Radier signifie que le membre ne sera plus inscrits sur aucune liste de la guilde. Il pourra à nouveau faire une demande d'inscription ou se faire inviter.">Radier</a>{%endif%}
{% elseif appm.actionPossible('bannirMembre') %}
            <a href="javascript:void(0);" onclick="organisation_mbsetetat('{{ path('organisationapp_bannir',{id:a.idaventurier.id,orga:orga.id}) }}','{{ path('organisationapp_listemembre',{'id':orga.id,actif:actif}) }}',$('#listeMembre{{pkey}}').parent())">Bannir</a>
{% endif %}
            {# @TODO <a href="javascript:void(0);" onclick="">Msg</a> #}
        </td>
{% if appm.actionPossible('gererDroits') and actif %}
        {% for d in droits %}
                <td><input id="orgambdroitcb-o{{a.idorganisation.id}}-a{{a.idaventurier.id}}-d{{d}}" type="checkbox" name="{{d}}" value="1" onchange="organisation_mbsetdroit({{a.idorganisation.id}},{{a.idaventurier.id}},'{{d}}',$(this).is(':checked'))" {% if a.is(d) %}checked="checked"{% endif %}/></td>
        {% endfor %}
 {% endif %}                   
    </tr>
{% endfor %}
</tbody>
</table>


<div id="listeMembre{{pkey}}-pager" class="pager"> <form> <span class="first pointer">&lt;&lt;</span> <span class="prev pointer">&lt;</span> <span class="smaller pagedisplay"></span> <span class="pointer next">&gt;</span> <span class="pointer last">&gt;&gt;</span> </form></div>

<script>
$('#listeMembre{{pkey}} > thead > tr > th ').tooltip();
$(document).ready(function() {
$("#listeMembre{{pkey}}").tablesorter({widthFixed:true,widgets:["zebra"]})
	.tablesorterPager({container: $("#listeMembre{{pkey}}-pager"), output: "{page} / {totalPages}"});
});
</script>

{% if appm.actionPossible('gererTitre') %}
<script> $('.orgaapp-orga-titre').editable(function(value, settings){
    var myobj = this;

    /* console.log($(this));
     console.log($(this).attr('class'));
     console.log(value);
     console.log(settings);*/
    var id = $(this).attr('data');
    start_loading();
    $.get (Routing.generate('organisationapp_settitre',{orga:{{orga.id}},id:id,titre:value}))
        .done(function(data){  })
        .fail(function (err) {
            // console.log(myobj.revert);
            $(myobj).html(myobj.revert);
            set_error($(err.responseText).find('h1').html());
        })
        .always(function(){ stop_loading(); });

     return(value);
  },{
      tooltip   : 'Cliquer pour éditer...'
  });
</script>
{% endif %}